version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=ecommerce
      - DB_USERNAME=root
    depends_on:
      - mysql
  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE=ecommerce
      - MYSQL_USER=root
